<script lang="ts">
  import type { PermissionExpression, TableInfo, ForeignKeyRelation, FKNavigationStep, PermissionValue, buildExistsFromPath, ColumnPath } from '@speajus/rlsify-types';
  import { schema, foreignKeys } from './stores/schema-store.js';
  import ConditionRow from './ConditionRow.svelte';

  interface Props {
    baseTable: string;
    expression?: PermissionExpression ;
    onUpdate: (expr: PermissionExpression | null) => void;
    debugLabel?: string;
  }

  let { baseTable, expression, onUpdate, debugLabel = 'VisualQueryBuilder' }: Props = $props();

  interface Condition {
    id: string;
    field: string;
    tablePath: string[]; // e.g., ['posts', 'user'] for posts.user.role
    /** FK navigation steps for cross-table references */
    fkPath?: FKNavigationStep[];
    operator: string;
    value: unknown;
    valueType: 'literal' | 'session' | 'column';
  }
  
  // Parse the initial expression into conditions
  // We need to declare state variables first, then parse
  let conditions = $state<Condition[]>([]);
  let logicMode = $state<'and' | 'or'>('and');

  // Track the last expression we parsed to avoid infinite loops
  let lastParsedExpression: PermissionExpression | undefined;

  // Track the last expression we generated to avoid re-parsing our own output
  let lastGeneratedExpression: PermissionExpression | null = null;

  // Flag to prevent updateExpression from being called during initialization
  let isLoadingFromExpression = false;

  // Get available tables through relationships
  let availableTables = $derived.by(() => {
    if (!$schema || !baseTable) return [];
    
    const tables = new Map<string, { table: TableInfo; path: string[]; relationship: string }>();
    const baseTableName = baseTable.split('.').pop() || baseTable;
    
    // Add base table
    const baseTableInfo = $schema.tables.find(t => t.name === baseTableName);
    if (baseTableInfo) {
      tables.set(baseTableName, { 
        table: baseTableInfo, 
        path: [baseTableName],
        relationship: 'base'
      });
    }
    
    // Add directly related tables via FK
    $foreignKeys.forEach(fk => {
      if (fk.sourceTable === baseTableName) {
        const targetTable = $schema.tables.find(t => t.name === fk.targetTable);
        if (targetTable) {
          tables.set(fk.targetTable, {
            table: targetTable,
            path: [baseTableName, fk.targetTable],
            relationship: `${fk.sourceColumn} → ${fk.targetTable}.${fk.targetColumn}`
          });
        }
      }
      if (fk.targetTable === baseTableName) {
        const sourceTable = $schema.tables.find(t => t.name === fk.sourceTable);
        if (sourceTable) {
          tables.set(fk.sourceTable, {
            table: sourceTable,
            path: [baseTableName, fk.sourceTable],
            relationship: `${fk.sourceTable}.${fk.sourceColumn} → ${fk.targetColumn}`
          });
        }
      }
    });
    
    return Array.from(tables.values());
  });

  // Initialize conditions from expression whenever it changes
  $effect(() => {
    // Only parse if the expression has changed AND it wasn't generated by us
    if (expression && expression !== lastParsedExpression) {
      // Check if this is the expression we just generated - skip re-parsing
      if (lastGeneratedExpression && JSON.stringify(expression) === JSON.stringify(lastGeneratedExpression)) {
        lastParsedExpression = expression;
        return;
      }

      isLoadingFromExpression = true;
      const { conditions: parsed, logicMode: mode } = parseExpressionToConditions(expression);
      conditions = parsed;
      logicMode = mode;
      lastParsedExpression = expression;
      // Use setTimeout to ensure all child components have finished initializing
      setTimeout(() => {
        isLoadingFromExpression = false;
      }, 0);
    }
  });

  function addCondition() {
    conditions.push({
      id: crypto.randomUUID(),
      field: '',
      tablePath: [baseTable.split('.').pop() || baseTable],
      fkPath: [],
      operator: '_eq',
      value: '',
      valueType: 'literal'
    });
  }
  
  function removeCondition(id: string) {
    conditions = conditions.filter(c => c.id !== id);
    updateExpression();
  }

  function updateCondition(id: string, updates: Partial<Condition>) {
    const index = conditions.findIndex(c => c.id === id);
    if (index !== -1) {
      conditions[index] = { ...conditions[index], ...updates };
      updateExpression();
    }
  }
  
  /**
   * Build an _exists expression from FK navigation path
   */
  function buildExistsExpression(
    fkPath: FKNavigationStep[],
    column: string,
    operator: string,
    value: PermissionValue
  ): PermissionExpression {
    if (fkPath.length === 0) {
      // No FK navigation - just a direct column reference
      return { [column]: { [operator]: value } } as PermissionExpression;
    }

    // Build nested _exists from inside out
    // Start with the innermost condition (the actual field comparison)
    let innerExpr: PermissionExpression = { [column]: { [operator]: value } } as PermissionExpression;

    // Work backwards through the steps
    for (const step of [...fkPath].reverse()) {
      // Link condition: join the tables via FK
      const linkCondition: PermissionExpression = {
        [step.toColumn]: { _eq: { column: `${step.fromTable}.${step.fromColumn}` } }
      } as PermissionExpression;

      // Combine link with inner expression
      innerExpr = {
        _exists: {
          _table: step.toTable,
          _where: { _and: [linkCondition, innerExpr] }
        }
      };
    }

    return innerExpr;
  }

  function updateExpression() {
    // Don't update if we're currently loading from an expression
    if (isLoadingFromExpression) {
      return;
    }

    if (conditions.length === 0) {
      onUpdate(null);
      return;
    }

    const fieldExpressions = conditions
      .filter(c => c.field && c.operator)
      .map(c => {
        // Prepare the value based on valueType
        let value: PermissionValue = c.value as PermissionValue;
        if (c.valueType === 'session') {
          value = { var: c.value as string, type: 'uuid' };
        } else if (c.valueType === 'column') {
          value = { column: c.value as string };
        }

        // If there's an FK path, generate _exists expression
        if (c.fkPath && c.fkPath.length > 0) {
          return buildExistsExpression(c.fkPath, c.field, c.operator, value);
        }

        // Simple field expression (no FK navigation)
        return {
          [c.field]: {
            [c.operator]: value
          }
        } as PermissionExpression;
      });

    if (fieldExpressions.length === 0) {
      lastGeneratedExpression = null;
      onUpdate(null);
      return;
    }

    let resultExpr: PermissionExpression;
    if (fieldExpressions.length === 1) {
      resultExpr = fieldExpressions[0];
    } else {
      resultExpr = {
        [`_${logicMode}`]: fieldExpressions
      } as PermissionExpression;
    }

    // Store the generated expression so we don't re-parse it
    lastGeneratedExpression = resultExpr;
    onUpdate(resultExpr);
  }
  
  function toggleLogicMode() {
    logicMode = logicMode === 'and' ? 'or' : 'and';
    updateExpression();
  }
  
  // Parse expression into conditions for display
  function parseExpressionToConditions(expr: PermissionExpression | undefined): { conditions: Condition[], logicMode: 'and' | 'or' } {
    if (!expr) return { conditions: [], logicMode: 'and' };

    const parsed: Condition[] = [];
    let mode: 'and' | 'or' = 'and';

    // Handle _and / _or at top level
    if ('_and' in expr && Array.isArray(expr._and)) {
      mode = 'and';
      expr._and.forEach((item: any) => {
        const cond = parseFieldExpression(item);
        if (cond) parsed.push(cond);
      });
    } else if ('_or' in expr && Array.isArray(expr._or)) {
      mode = 'or';
      expr._or.forEach((item: any) => {
        const cond = parseFieldExpression(item);
        if (cond) parsed.push(cond);
      });
    } else {
      // Single field expression
      const cond = parseFieldExpression(expr);
      if (cond) parsed.push(cond);
    }

    return { conditions: parsed, logicMode: mode };
  }

  function parseFieldExpression(expr: any): Condition | null {
    // Skip _exists and other complex operators for now
    if ('_exists' in expr || '_not' in expr) {
      return null;
    }

    // Find the field name (first key that's not an operator)
    const fieldName = Object.keys(expr).find(k => !k.startsWith('_'));
    if (!fieldName) return null;

    const fieldValue = expr[fieldName];
    if (!fieldValue || typeof fieldValue !== 'object') return null;

    // Find the operator
    const operator = Object.keys(fieldValue).find(k => k.startsWith('_'));
    if (!operator) return null;

    const value = fieldValue[operator];

    // Determine value type and extract actual value
    let valueType: 'literal' | 'session' | 'column' = 'literal';
    let actualValue: any = value;

    if (value && typeof value === 'object') {
      if ('var' in value) {
        valueType = 'session';
        actualValue = value.var;
      } else if ('column' in value) {
        valueType = 'column';
        actualValue = value.column;
      }
    }

    const tableName = baseTable.split('.').pop() || baseTable;

    return {
      id: crypto.randomUUID(),
      field: fieldName,
      tablePath: [tableName],
      operator,
      value: actualValue,
      valueType
    };
  }


</script>

<div class="visual-query-builder">
  <div class="builder-header">
    <h3>Visual Query Builder</h3>
    <p class="hint">Build permission rules without writing SQL</p>
  </div>
  
  {#if conditions.length > 1}
    <div class="logic-toggle">
      <span>Match</span>
      <button class="logic-btn {logicMode === 'and' ? 'active' : ''}" onclick={toggleLogicMode}>
        {logicMode === 'and' ? 'ALL' : 'ANY'}
      </button>
      <span>of the following conditions:</span>
    </div>
  {/if}
  
  <div class="conditions-list">
    {#each conditions || [] as condition (condition.id)}
      <ConditionRow
        {condition}
        {availableTables}
        onUpdate={(updates) => updateCondition(condition.id, updates)}
        onRemove={() => removeCondition(condition.id)}
      />
    {/each}
  </div>
  
  <button class="add-condition-btn" onclick={addCondition}>
    + Add Condition
  </button>
</div>

<style>
  .visual-query-builder {
    display: flex;
    flex-direction: column;
    gap: 1rem;
    padding: 1rem;
    background: var(--bg-tertiary);
    border-radius: 8px;
  }

  .builder-header h3 {
    margin: 0 0 0.25rem 0;
    font-size: 1rem;
    color: var(--text-primary);
  }

  .builder-header .hint {
    margin: 0;
    font-size: 0.875rem;
    color: var(--text-muted);
  }

  .logic-toggle {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.75rem;
    background: var(--bg-secondary);
    border: 1px solid var(--border-color);
    border-radius: 6px;
    font-size: 0.875rem;
    color: var(--text-secondary);
  }

  .logic-btn {
    padding: 0.375rem 0.75rem;
    background: var(--bg-tertiary);
    border: 1px solid var(--border-color);
    border-radius: 4px;
    color: var(--text-primary);
    font-weight: 600;
    cursor: pointer;
    transition: all 0.2s;
  }

  .logic-btn:hover {
    background: var(--bg-hover);
    border-color: var(--border-hover);
  }

  .logic-btn.active {
    background: var(--accent-primary);
    border-color: var(--accent-primary);
    color: white;
  }

  .conditions-list {
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
  }

  .add-condition-btn {
    padding: 0.75rem;
    background: var(--bg-secondary);
    border: 1px dashed var(--border-color);
    border-radius: 6px;
    color: var(--text-secondary);
    font-size: 0.875rem;
    font-weight: 500;
    cursor: pointer;
    transition: all 0.2s;
  }

  .add-condition-btn:hover {
    background: var(--bg-hover);
    border-color: var(--accent-primary);
    border-style: solid;
    color: var(--accent-primary);
  }
</style>

